In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.special as special 
from scipy.optimize import curve_fit
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [64]:
#Cargar archivo csv des seaborn

# Verificar sin indice 
df= pd.read_csv('DATANN.csv')
df

Unnamed: 0  Administrador  Usuario  botón correcto  \
0              0              1        2             1.0   
1              1              1        2             0.0   
2              2              1        2             1.0   
3              3              1        2             0.0   
4              4              1        2             0.0   
...          ...            ...      ...             ...   
5860        5860              0       30             1.0   
5861        5861              0        3             0.0   
5862        5862              0        3             0.0   
5863        5863              0        3             0.0   
5864        5864              0        3             0.0   

      tiempo de interacción  mini juego  número de interacción  \
0                  5.399169           8                    1.0   
1                  1.283400           8                    2.0   
2                  2.700226           8                    3.0   
3                  3.050262           8                    4.0   
4                  4.750256           8                    5.0   
...                     ...         ...                    ...   
5860               7.099429           1                    4.0   
5861               2.135419           0                    1.0   
5862               2.135419           0                    1.0   
5863               2.135419           0                    1.0   
5864               2.135419          10                    1.0   

      color presionado  dificultad  Juego  auto push  tiempo de lección  \
0                    3           0      0        0.0           0.000000   
1                    0           0      0        0.0           0.000000   
2                    1           0      0        0.0           0.000000   
3                    1           0      0        0.0           0.000000   
4                    1           0      0        0.0           0.000000   
...                ...         ...    ...        ...                ...   
5860                 1           0      0        0.0           7.461668   
5861                 1           2      0        0.0           0.000000   
5862                 1           2      0        0.0           2.271806   
5863                 1           2      0        0.0           2.271806   
5864                 1           2      0        0.0           2.271806   

      tiempo de sesión  
0             0.000000  
1             0.000000  
2             0.000000  
3             0.000000  
4             0.000000  
...                ...  
5860        332.240000  
5861          0.000000  
5862          0.000000  
5863          6.478299  
5864          6.478299  

[5865 rows x 13 columns]

In [70]:
df10= df.groupby(['botón correcto'])['botón correcto'].count()
df10.info

<bound method Series.info of botón correcto
0.0    2668
1.0    3197
Name: botón correcto, dtype: int64>

### Correlación Lógistica

In [65]:
#verificar los valores sin repetirse de una columna
unico = np.unique(df['botón correcto'])
unico

array([0., 1.])

**Primer caso**

In [66]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=df[['mini juego', 'Juego', 'número de interacción']]
vars_Dep=df[['botón correcto']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =1)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('sensibilidad del modelo: ')
print(sensibilidad)


Matriz de confusión: 
[[353 462]
 [176 769]]

precision del modelo: 
0.6246953696181966

exactitud del modelo
0.6375

sensibilidad del modelo: 
0.8137566137566138


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Segundo caso

In [67]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=df[['Usuario', 'mini juego', 'color presionado']]
vars_Dep=df[['Juego']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =0)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('sensibilidad del modelo: ')
print(sensibilidad)


Matriz de confusión: 
[[1064   82]
 [  12  602]]

precision del modelo: 
0.9888475836431226

exactitud del modelo
0.946590909090909

sensibilidad del modelo: 
0.9284467713787086


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Tercer caso

In [68]:
#verificar los valores sin repetirse de una columna
unico = np.unique(df['auto push'])
unico

array([0., 1.])

In [69]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=df[['Usuario', 'mini juego', 'color presionado']]
vars_Dep=df[['auto push']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =1)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('sensibilidad del modelo: ')
print(sensibilidad)


Matriz de confusión: 
[[1349  380]
 [  10   21]]

precision del modelo: 
0.05236907730673317

exactitud del modelo
0.7784090909090909

sensibilidad del modelo: 
0.6774193548387096


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Punto 5

### usuarios

In [45]:
usuario_1=df.copy()
usuario_2=df.copy()
usuario_3=df.copy()
usuario_4=df.copy()
usuario_5=df.copy()

In [46]:
#verificar los valores sin repetirse de una columna
unico = np.unique(usuario_1['Usuario'])
unico

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

### Valentín 

In [47]:
#convertimos una variable categorica  dicotomica
usuario_1['Usuario']= usuario_1['Usuario'].replace([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32], 'demás usuarios')

#convertimos una variable categorica  dicotomica
usuario_1['Usuario']= usuario_1['Usuario'].replace([12], 'Valentin')


In [48]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=usuario_1[['tiempo de interacción', 'botón correcto', 'número de interacción']]
vars_Dep=usuario_1[['Usuario']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label ='Valentin')
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='Valentin')
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[ 30  13]
 [925 792]]

precision del modelo: 
0.031413612565445025

exactitud del modelo
0.46704545454545454

sensibilidad del modelo: 
0.6976744186046512


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Yael David

In [49]:
#convertimos una variable categorica  dicotomica
usuario_2['Usuario']= usuario_2['Usuario'].replace([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32], 'demás usuarios')

#convertimos una variable categorica  dicotomica
usuario_2['Usuario']= usuario_2['Usuario'].replace([11], 'Yael David')


In [50]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=usuario_2[['tiempo de interacción', 'botón correcto', 'número de interacción']]
vars_Dep=usuario_2[['Usuario']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label ='Yael David')
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='Yael David')
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[  23   20]
 [ 660 1057]]

precision del modelo: 
0.03367496339677892

exactitud del modelo
0.6136363636363636

sensibilidad del modelo: 
0.5348837209302325


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Yeremy Jazmin

In [51]:
#convertimos una variable categorica  dicotomica
usuario_3['Usuario']= usuario_3['Usuario'].replace([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32], 'demás usuarios')

#convertimos una variable categorica  dicotomica
usuario_3['Usuario']= usuario_3['Usuario'].replace([24], 'Yeremy jazmin')


In [52]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=usuario_3[['tiempo de interacción', 'botón correcto', 'número de interacción']]
vars_Dep=usuario_3[['Usuario']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label ='Yeremy jazmin')
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='Yeremy jazmin')
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[ 18   3]
 [911 828]]

precision del modelo: 
0.0193756727664155

exactitud del modelo
0.48068181818181815

sensibilidad del modelo: 
0.8571428571428571


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Ramiro

In [54]:
#convertimos una variable categorica  dicotomica
usuario_4['Usuario']= usuario_4['Usuario'].replace([ 0,  1,  2,  3,  4,  5, 7,  8,  9, 10,11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,24, 25, 26, 27, 28, 29, 30, 31, 32], 'demás usuarios')

#convertimos una variable categorica  dicotomica
usuario_4['Usuario']= usuario_4['Usuario'].replace([6], 'Ramiro')


In [55]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=usuario_4[['tiempo de interacción', 'botón correcto', 'número de interacción']]
vars_Dep=usuario_4[['Usuario']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label ='Ramiro')
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='Ramiro')
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[ 60  15]
 [976 709]]

precision del modelo: 
0.05791505791505792

exactitud del modelo
0.4369318181818182

sensibilidad del modelo: 
0.8


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Irving 

In [56]:
#convertimos una variable categorica  dicotomica
usuario_5['Usuario']= usuario_5['Usuario'].replace([ 0,  1,  2,  3,  4,  5,6, 7,  8,  9, 10,11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,24, 25, 26, 27, 28, 29, 30, 31], 'demás usuarios')

#convertimos una variable categorica  dicotomica
usuario_5['Usuario']= usuario_5['Usuario'].replace([32], 'Irving')


In [57]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=usuario_5[['tiempo de interacción', 'botón correcto', 'número de interacción']]
vars_Dep=usuario_5[['Usuario']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label ='Irving')
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='Irving')
print('sensibilidad del modelo: ')
print(sensibilidad)

c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Matriz de confusión: 
[[   1    0]
 [ 511 1248]]

precision del modelo: 
0.001953125

exactitud del modelo
0.709659090909091

sensibilidad del modelo: 
1.0
